import { Button, ButtonGroup, Container, Heading } from "@chakra-ui/react";
import axios from "axios";
import Head from "next/head";
import router from "next/router";
//import Link from "next/link";
import { env } from "~/env.mjs";
//import { env } from "process";

export default function Home() {
  return (
    <>
      <Head>
        <title>Admin APP</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">  */}
        {/* <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            {env.NEXT_PUBLIC_BACKEND_BASE_URL}
          </h1>
        </div>  */}
        {/* <button style={{color: "white"}}>LOGIN</button> */}
        <Container marginTop={4}>
          <Heading>Mis Ventas</Heading>
        <ButtonGroup>
          <Button colorScheme="blue" onClick={()=>{
            router.push("/login")
          }}>Iniciar sesión</Button>

          <Button 
            colorScheme="green" 
            onClick={ ()=> {
            axios.get(`${env.NEXT_PUBLIC_BACKEND_BASE_URL}/sales`, { withCredentials: true})
          }}
          >
          Get sales
          </Button>

          <Button 
            colorScheme="purple" 
            onClick={ ()=> {
            axios.post(`${env.NEXT_PUBLIC_BACKEND_BASE_URL}/sales`,
            { operation_date: new Date(), total_amount: 2500 }, 
            { withCredentials: true})
          }}
          >
          Create sales
          </Button>
        </ButtonGroup>  
        </Container>        
      {/* </main> */}
    </>
  );
}
