import { Button, ButtonGroup, Card, Container, Heading } from "@chakra-ui/react";
import axios from "axios";
import Head from "next/head";
import router from "next/router";
//import Link from "next/link";
import { env } from "~/env.mjs";
//import { env } from "process";

export default function Home() {
  return (
    <>
      <Head>
        <title>Admin APP</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container marginTop={8}>
        <Button
          colorScheme="blue"
          mb={2}
          alignSelf={"end"}
          onClick={() => {
            router.push("/login")
          }}>Iniciar sesión
        </Button>

        <Card p={4}>
          <Heading>Mis Ventas</Heading>
          <ButtonGroup mt={8}>
            <Button
              colorScheme="green"
              onClick={() => {
                router.push('/sales/new')
              }}>Nueva venta</Button>

            <Button
              colorScheme="purple"
              onClick={() => {
                router.push('clients')
              }}>Clients</Button>
          </ButtonGroup>

        </Card>

      </Container>
    </>
  )
}
